

-- CREATION DB Contoso direct Sales


CREATE DATABASE [Contoso Direct Sales]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Contoso Direct Sales', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Contoso Direct Sales.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Contoso Direct Sales_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\Contoso Direct Sales_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [Contoso Direct Sales] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [Contoso Direct Sales] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET ARITHABORT OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [Contoso Direct Sales] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [Contoso Direct Sales] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [Contoso Direct Sales] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET  DISABLE_BROKER 
GO
ALTER DATABASE [Contoso Direct Sales] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [Contoso Direct Sales] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [Contoso Direct Sales] SET  READ_WRITE 
GO
ALTER DATABASE [Contoso Direct Sales] SET RECOVERY FULL 
GO
ALTER DATABASE [Contoso Direct Sales] SET  MULTI_USER 
GO
ALTER DATABASE [Contoso Direct Sales] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [Contoso Direct Sales] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [Contoso Direct Sales] SET DELAYED_DURABILITY = DISABLED 
GO
USE [Contoso Direct Sales]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [Contoso Direct Sales]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [Contoso Direct Sales] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO


