CREATE DATABASE [ML_Titanic]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'ML_Titanic', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ML_Titanic.mdf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'ML_Titanic_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\ML_Titanic_log.ldf' , SIZE = 8192KB , FILEGROWTH = 65536KB )
GO
ALTER DATABASE [ML_Titanic] SET COMPATIBILITY_LEVEL = 150
GO
ALTER DATABASE [ML_Titanic] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [ML_Titanic] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [ML_Titanic] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [ML_Titanic] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [ML_Titanic] SET ARITHABORT OFF 
GO
ALTER DATABASE [ML_Titanic] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [ML_Titanic] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [ML_Titanic] SET AUTO_CREATE_STATISTICS ON(INCREMENTAL = OFF)
GO
ALTER DATABASE [ML_Titanic] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [ML_Titanic] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [ML_Titanic] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [ML_Titanic] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [ML_Titanic] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [ML_Titanic] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [ML_Titanic] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [ML_Titanic] SET  DISABLE_BROKER 
GO
ALTER DATABASE [ML_Titanic] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [ML_Titanic] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [ML_Titanic] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [ML_Titanic] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [ML_Titanic] SET  READ_WRITE 
GO
ALTER DATABASE [ML_Titanic] SET RECOVERY FULL 
GO
ALTER DATABASE [ML_Titanic] SET  MULTI_USER 
GO
ALTER DATABASE [ML_Titanic] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [ML_Titanic] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [ML_Titanic] SET DELAYED_DURABILITY = DISABLED 
GO
USE [ML_Titanic]
GO
ALTER DATABASE SCOPED CONFIGURATION SET LEGACY_CARDINALITY_ESTIMATION = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET LEGACY_CARDINALITY_ESTIMATION = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 0;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET MAXDOP = PRIMARY;
GO
ALTER DATABASE SCOPED CONFIGURATION SET PARAMETER_SNIFFING = On;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET PARAMETER_SNIFFING = Primary;
GO
ALTER DATABASE SCOPED CONFIGURATION SET QUERY_OPTIMIZER_HOTFIXES = Off;
GO
ALTER DATABASE SCOPED CONFIGURATION FOR SECONDARY SET QUERY_OPTIMIZER_HOTFIXES = Primary;
GO
USE [ML_Titanic]
GO
IF NOT EXISTS (SELECT name FROM sys.filegroups WHERE is_default=1 AND name = N'PRIMARY') ALTER DATABASE [ML_Titanic] MODIFY FILEGROUP [PRIMARY] DEFAULT
GO



CREATE TABLE dbo.test_Titanic (
Passenger int not null,
Pclass	int not null,
Passenger_name varchar(100) null,	
Sex	varchar(100) null,
Age	float null,
SibSp	int null,
Parch	int null,
Ticket	varchar(100) null,
Fare	float null,
Cabin	varchar(100) null,
Embarked varchar(100)
)


CREATE TABle dbo.Submission_Titanic (
Passenger int not null,
Survived int  not null)